[project]
site_name = "codeshell · TMW"
site_description = "Guides, scripts, snippets and discussions on dev topics."
site_url = "https://codeshell.on.state.ovh"
site_author = "codeshell"
copyright = """
Copyright &copy; 2026 TMW
"""
extra_css = [
    "_static/stylesheets/admonition.css",
    "_static/stylesheets/custom_attributes.css",
    "_static/stylesheets/customization.css",
]
extra_javascript = [
    "_static/javascripts/mathjax.js",
    "_static/javascripts/snippets.js",
]
repo_url = "https://github.com/codeshell/codeshell.on.state.ovh"

[project.theme]
#custom_dir = "overrides"
#logo = "_static/images/logo.png"
favicon = "_static/images/favicons.png"
language = "en"
features = [
    "announce.dismiss",
    #"content.action.edit", # source files not public
    #"content.action.view", # source files not public
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    # "header.autohide",
    # "navigation.expand",
    "navigation.footer",
    "navigation.indexes",          # section groups can have content via index.md files
    "navigation.instant",
    "navigation.instant.prefetch",
    #"navigation.instant.progress",
    "navigation.path",     # breadcrumbs
    "navigation.prune",    # only the visible navigation items are included in the rendered HTML
    "navigation.sections", # when combined with tabs, section groups are level 2 folders, else level 1
    "navigation.tabs",
    #"navigation.tabs.sticky",
    "navigation.top",      # back-to-top button appears when scrolling up
    "navigation.tracking",
    "search.highlight",
    "toc.follow",          # sidebar is automatically scrolled so that the active anchor is always visible
    #"toc.integrate",                   # page toc is moved from (right) sidebar into navigation (left)
]

[project.theme.icon]
logo = "lucide/terminal"

[project.theme.icon.tag]
default = "lucide/hash"
html = "fontawesome/brands/html5"
js = "fontawesome/brands/js"
css = "fontawesome/brands/css3"

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/codeshell"
name = "GitHub"

[[project.extra.social]]
icon = "simple/matrix"
link = "https://matrix.to/#/#codeshell:tchncs.de"
name = "Matrix"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/MNWw5hZsux"
name = "Discord"

[project.extra.tags]
HTML5 = "html"
JavaScript = "js"
CSS = "cs"

# [project.extra]
# alternate = [
#     { name = "English", link = "/en/", lang = "en" },
#     { name = "Deutsch", link = "/de/", lang = "de" }
# ]

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.snippets]
auto_append = ["includes/abbreviations.md"]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
    { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
    { name = "dataview", class = "dataview", format = "pymdownx.superfences.fence_div_format" },
    { name = "folderv", class = "folderv", format = "pymdownx.superfences.fence_div_format" },
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]
[[project.markdown_extensions.zensical.extensions.preview.configurations]] # array!
targets.include = [
    "setup/extensions/*",
    "blog/*",
    "guides/*",
    "topics/*",
    "index.md",
]
