name: Publish Documentation
on:
  push:
    branches:
      - main
    paths: 
      - 'overrides/**'
      - 'includes/**'
      - 'docs' # contains submodule pointer
      - 'docs/**'
  workflow_dispatch:
  workflow_call:
    inputs:
      FETCH_SUBMODULE:
        description: "Fetch submodule for the docs"
        required: false
        default: true
        type: boolean
    secrets:
      GH_PAT:
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

env:
  customZensical: ${{ vars.ZENSICAL_LINUX_WHL }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN}}
          submodules: recursive
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v8.2.0
        with:
            enable-cache: auto
            cache-dependency-glob: "uv.lock"
      - run: uv python install 3.14
      - run: uv sync
      - name: Fetching custom Zensical build
        run: |
          curl -L ${{ env.customZensical }} -o /tmp/zensical.whl
          uv pip install /tmp/zensical.whl
        id: fetch-custom
        if:  ${{ env.customZensical != '' }}
      - run: uv run --no-sync zensical build --clean
        if: ${{ steps.fetch-custom.outcome == 'success' }}
      - run: uv run zensical build --clean
        if:  ${{ steps.fetch-custom.outcome == 'skipped' }}
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
      - uses: actions/deploy-pages@v5
        id: deployment
