name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_PAT:
        required: true
  schedule:
    - cron: "00 10 * * 1,4"

permissions:
  contents: read
  issues: write

env:
  ISSUE: 13

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN}}
          submodules: recursive
          fetch-depth: 0

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --root-dir "$(pwd)/docs"
            --scheme https --scheme http --scheme mailto
            --verbose --no-progress './**/*.md' './**/*.html'
            --exclude-path 'playground\.md$'
          fail: false
          output: lychee/out.md
          workingDirectory: .

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v6
        with:
          title: Link Checker Report
          issue-number: ${{ env.ISSUE }}
          content-filepath: ./lychee/out.md
          labels: report, automated issue
